name: CoinExchange
main: me.becja10.CoinExchange.CoinExchange
author: 10becja
version: 1.1
description: A Coin Plugin
commands:
  addcoins:
    description: adds coins to a player
    usage: /<command> <player> <amount>
  removecoins:
    description: Removes coins from a player
    usage: /<command> <player> <amount>
  viewcoins:
    description: Views how many coins you or another players has
    usage: /<command> (player)
  spendcoins:
    description: Open a GUI to spend your coins
    usage: /<command>
  reloadcoins:
    description: Reloads the config
    usage: /<command>
  cecustomitem:
    description: Adds a custom item that can be used in inventory menu
    usage: /<command> <item key>